### ISSUE TITLE
Feature Request:  Add wiki info to official documentation

### ISSUE THREAD

**Issue by larryclaman** [cgillum/easyauth#10]
The page https://github.com/cgillum/easyauth/wiki/Advanced-Application-Settings contains information that I cannot find documented elsewhere.  As much as I appreciate you documenting this info 😊, my request is that you add this to the official Microsoft Web App documentation.

**Comment by cgillum** [comment]
Official docs are finally available! https://docs.microsoft.com/azure/app-service/reference-app-settings#authentication--authorization
