### ISSUE TITLE
Azure App Service Portal showing blank screen when there are configuration issues in the App Registration

### ISSUE THREAD

**Issue by Katuri09** [cgillum/easyauth#11]
Azure Portal shows blank screen on the Authentication blade when there are misconfigurations on the App Service or Function app.
It doesn't provide any option to disable and reconfigure the EasyAuth configurations.

The only alternative way is to use the control plane API's to disable and then use the portal back to reconfigure EasyAuth.
Can Portal UI be improved to display errors and provide options to reconfigure EasyAuth if there are issues with the current app registration?

**Comment by cgillum** [comment]
Hi @Katuri09. That definitely sounds problematic. This repo unfortunately isn't a good place to report issues. Would you mind opening an Azure support ticket to help make sure the right people take a look at this issue/request?
