### ISSUE TITLE
Ability to disable thread principal assignment

### ISSUE THREAD

**Issue by cgillum** [cgillum/easyauth#2]
There are some scenarios where the behavior of assigning the thread principal is not desirable.

Here is an example case that came up in StackOverflow: https://stackoverflow.com/questions/22495494/password-protecting-an-azure-website-not-just-via-web-app-form/28121420?noredirect=1#comment78705778_28121420

A simple solution would be an app setting which can disable this behavior.

**Comment by svenkle** [comment]
Any updates on this issue @cgillum ? I'm happy to assist/contribute although I don't know if you guys are comfortable making this open or not.

**Comment by cgillum** [comment]
Unfortunately we're not in a position to make this open right now. I'm going to take a look at this work item next week.

**Comment by mattyindustries** [comment]
Hi @cgillum 

@svenkle has moved on from the company he was working on this issue for and I've taken over.

Is there a list somewhere I can be added to for updates about this issue or is this the best forum?

Mat

**Comment by cgillum** [comment]
Hi Mat. This is the best forum for now. The current status is that this is scheduled to be deployed in December.

**Comment by cgillum** [comment]
Sorry for the delayed response. This can now be achieved by creating an app setting named **WEBSITE_AUTH_DISABLE_IDENTITY_FLOW** and setting it's value to **true**.
