### ISSUE TITLE
Add upn to id-token for external users in AAD

### ISSUE THREAD

**Issue by alexjebens** [cgillum/easyauth#9]
I would like to have the upn in the X-MS-TOKEN-AAD-ID-TOKEN header so that I do not have to make a separate Graph Request based on the oid every time someone calls one of my endpoints. The property is set for internal users whereas guest users only have unique_name, which is not the same (e.g outlook: 
unique_name: live.com#user@host.com vs. upn: user_host.com#EXT#@aadtenant).

Particularly for Azure Functions this creates a lot of unnecessary traffic and therefore latency.

I would be happy to do the changes myself and submit a pull request if you can point me to the repository.

**Comment by cgillum** [comment]
Unfortunately, this is not something that Easy Auth controls. Rather, the token issuer determines which claims are available. We just pass the token we get along as part of this header. If there is a login parameter that determines this, we can add support for that login parameter (if we don't already expose it).
